import type { Metadata } from 'next'
import FreeShipping from './components/FreeShipping'
import Navbar from './components/Navbar'
import NavbarMobile from './components/NavbarMobile'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<FreeShipping />
				<Navbar />
				<NavbarMobile />
				{children}
			</body>
		</html>
	)
}
